
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmnebontltglqxdbprqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbmVib250bHRnbHF4ZGJwcnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTMyMTksImV4cCI6MjA1ODM2OTIxOX0.0D8p_k5zY7lxT-s2Y2eOLs_7rbCXZfl5zO5i1OlvFdw";

// Create the Supabase client with proper configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
